emby:
  host: http://192.168.0.109:8096            # emby 访问地址 (非 docker 内网)
  mount-path: /data                          # rclone/cd2 挂载的本地磁盘路径, 如果 emby 是容器部署, 这里要配的就是容器内部的挂载路径
  api-key: 2f8sng5sjd5enm65df5e4s12q96324fwc # emby api key 可以在 emby 管理后台配置
  episodes-unplay-prior: true                # 是否修改剧集排序, 让未播的剧集靠前排列; 启用该配置时, 会忽略原接口的分页机制
alist:
  host: http://192.168.0.109:5244            # alist 访问地址 (非 docker 内网)
  token: alist-xxxxx                         # alist api key 可以在 alist 管理后台查看
video-preview:
  enable: true                               # 是否开启 alist 转码资源信息获取
  containers:                                # 对哪些视频容器获取转码资源信息
    - mp4
    - mkv
path:
  # emby 挂载路径和 alist 真实路径之间的前缀映射
  # 冒号左边表示本地挂载路径, 冒号右边表示 alist 的真实路径
  # 这个配置请再三确认配置正确, 可以减少很多不必要的网络请求
  emby2alist: 
    - /movie:/电影
    - /music:/音乐
    - /show:/综艺
    - /series:/电视剧
    - /sport:/运动
    - /animation:/动漫
cache:
  # 是否启用缓存中间件
  # 推荐启用, 既可以缓存 Emby 的大接口以及静态资源, 又可以缓存网盘直链, 避免频繁请求
  enable: true
  # 缓存过期时间
  #
  # 可配置单位: d(天), h(小时), m(分钟), s(秒)
  #
  # 该配置不会影响特殊接口的缓存时间
  # 比如直链获取接口的缓存时间固定为 10m, 字幕获取接口的缓存时间固定为 30d
  expired: 1d
ssl:
  enable: true        # 是否启用 https
  # 是否使用单一端口
  #
  # 不启用: 程序会在 8094 端口上监听 https 连接, 不监听 http
  # 启用: 程序会在 8094 端口上监听 https 连接, 在 8095 端口上监听 http 连接
  single-port: false
  key: testssl.cn.key # 私钥文件名
  crt: testssl.cn.crt # 证书文件名