emby:
  host: http://192.168.0.109:8096            # emby 访问地址
  mount-path: /data                          # rclone/cd2 挂载的本地磁盘路径, 如果 emby 是容器部署, 这里要配的就是容器内部的挂载路径
  episodes-unplay-prior: true                # 是否修改剧集排序, 让未播的剧集靠前排列; 启用该配置时, 会忽略原接口的分页机制
  resort-random-items: true                  # 是否重排序随机列表, 对 emby 的排序结果进行二次重排序, 使得列表足够随机
  # 代理异常处理策略
  # origin: 重定向回源服务器
  # reject: 拒绝处理
  proxy-error-strategy: origin
  # 图片质量, 默认请求原图
  # 配置范围: [1, 100]
  # 建议范围: [70, 90]
  # 具体数值根据自己的实际情况作调整
  images-quality: 100
  strm:                                      # 远程视频 strm 配置
    # 路径映射, 将 strm 文件内的路径片段替换成指定路径片段
    # 可配置多个映射, 每个映射需要有 2 个片段, 使用 [=>] 符号进行分割, 程序自上而下映射第一个匹配的结果
    # 这个配置的映射是比较灵活的, 不一定必须按照前缀映射, 可以直接将地址中间的片段给替换掉
    #
    # 举个栗子
    # strm 文件内容: https://test-res.com:8094/1.mp4, 替换结果: http://localhost:8095/1.mp4 
    # strm 文件内容: https://test-res.com:12138/test-id-12138.mp4, 替换结果: https://test-res.com:10086/test-id-12138.mp4 
    path-map:
      - https://test-res.com:8094 => http://localhost:8095
      - 12138 => 10086

# 该配置仅针对通过磁盘挂载方式接入的网盘, 如果你使用的是 strm, 可忽略该配置
alist:
  host: http://192.168.0.109:5244            # alist 访问地址
  token: alist-xxxxx                         # alist api key 可以在 alist 管理后台查看

# 该配置项目前只对阿里云盘生效, 如果你使用的是其他网盘, 请直接将 enable 设置为 false
video-preview:
  enable: true                               # 是否开启 alist 转码资源信息获取
  containers:                                # 对哪些视频容器获取转码资源信息
    - mp4
    - mkv
  ignore-template-ids:                       # 忽略哪些转码清晰度
    - LD
    - SD

path:
  # emby 挂载路径和 alist 真实路径之间的前缀映射
  # 冒号左边表示本地挂载路径, 冒号右边表示 alist 的真实路径
  # 这个配置请再三确认配置正确, 可以减少很多不必要的网络请求
  emby2alist: 
    - /movie:/电影
    - /music:/音乐
    - /show:/综艺
    - /series:/电视剧
    - /sport:/运动
    - /animation:/动漫

cache:
  # 是否启用缓存中间件
  # 推荐启用, 既可以缓存 Emby 的大接口以及静态资源, 又可以缓存网盘直链, 避免频繁请求
  enable: true
  # 缓存过期时间
  #
  # 可配置单位: d(天), h(小时), m(分钟), s(秒)
  #
  # 该配置不会影响特殊接口的缓存时间
  # 比如直链获取接口的缓存时间固定为 10m, 字幕获取接口的缓存时间固定为 30d
  expired: 1d

ssl:
  enable: false       # 是否启用 https
  # 是否使用单一端口
  #
  # 启用: 程序会在 8094 端口上监听 https 连接, 不监听 http
  # 不启用: 程序会在 8094 端口上监听 https 连接, 在 8095 端口上监听 http 连接
  single-port: false
  key: testssl.cn.key # 私钥文件名
  crt: testssl.cn.crt # 证书文件名

log:
  # 是否禁用控制台彩色日志
  #
  # 程序默认是输出彩色日志的,
  # 如果你的终端不支持彩色输出, 并且多出来一些乱码字符
  # 可以将该项设置为 true
  disable-color: false