name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送符合这个模式的标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]  # 指定目标架构
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}  # 多架构构建
          push: false
          tags: |
            ambitiousjun/go-emby2alist:${{ github.ref_name }}
            ambitiousjun/go-emby2alist:latest

      - name: Push Docker manifest (multi-architecture)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ambitiousjun/go-emby2alist:${{ github.ref_name }}
            ambitiousjun/go-emby2alist:latest

      - name: Logout from Docker Hub
        run: docker logout
